import { assert, assertEquals } from "@std/assert";

import {
  horoscopeResponseSchema,
  LIFE_AREAS,
  type THoroscopeData,
} from "../../functions/generate-horoscopes/astrology.ts";
import { toHoroscopeRow } from "../../functions/generate-horoscopes/row.ts";

// DEX-145.

/** A response whose life areas are all `fill`, except `standout` at 5. */
function dataWith(standout?: string, fill = 1): THoroscopeData {
  return {
    text: "A quiet day.",
    overall_rating: 4,
    tips: ["One.", "Two.", "Three."],
    life_area_focus: LIFE_AREAS.map((area) => ({
      area,
      rating: area === standout ? 5 : fill,
    })),
    date: "2026-08-12",
  };
}

Deno.test("the row uses the requested sign, not the upstream echo", () => {
  // The upstream echoes a capitalized display name ("Aries") that would not
  // match the enum. The sign we asked for decides the row's identity.
  assertEquals(toHoroscopeRow("aries", dataWith()).sun_sign, "aries");
});

Deno.test("the date comes from the response, not the local clock", () => {
  // We ask for a specific day and the upstream echoes the day it answered for,
  // so it stays the authority. `index.ts` reports any disagreement to Sentry.
  assertEquals(toHoroscopeRow("aries", dataWith()).date, "2026-08-12");
});

Deno.test("each life area lands in its own column", () => {
  // Twelve same-typed columns is where `rating_love: ratings.learning` would
  // compile clean and show the wrong number.
  for (const area of LIFE_AREAS) {
    const row = toHoroscopeRow("aries", dataWith(area)) as unknown as Record<
      string,
      unknown
    >;

    for (const other of LIFE_AREAS) {
      assertEquals(
        row[`rating_${other}`],
        other === area ? 5 : 1,
        `singling out ${area} changed rating_${other}`,
      );
    }
  }
});

Deno.test("the text, overall rating, and tips are carried across", () => {
  const row = toHoroscopeRow("taurus", dataWith());

  assertEquals(row.text, "A quiet day.");
  assertEquals(row.overall_rating, 4);
  assertEquals(row.tips, ["One.", "Two.", "Three."]);
});

Deno.test("sentiment is never written", () => {
  // Generated from `overall_rating` in the database — the whole point is
  // that the tint and the rating cannot drift apart.
  assert(
    !("sentiment" in toHoroscopeRow("gemini", dataWith())),
    "sentiment is generated by Postgres and must not appear in the insert",
  );
});

Deno.test("an added upstream field never reaches the insert", () => {
  // The guarantee comes from zod stripping unknown keys in `parse`, so this
  // asserts the pair end to end — an unknown column fails all twelve rows.
  const parsed = horoscopeResponseSchema.parse({
    success: true,
    data: {
      ...dataWith(),
      sign_emoji: "♈",
      word_count: 35,
      planetary_influences: [{ planet: "Chiron" }],
      brand_new: "x",
    },
  }).data;

  const row = toHoroscopeRow("cancer", parsed) as unknown as Record<
    string,
    unknown
  >;

  for (
    const key of [
      "sign_emoji",
      "word_count",
      "planetary_influences",
      "brand_new",
    ]
  ) {
    assert(!(key in row), `${key} must not reach the insert`);
  }
});
