// AstrologyAPI client for DEX-84.
//
// Everything in this module is pure or takes its `fetch` as an argument, so the
// whole upstream contract — the request shape, the response validation, and the
// date format — is testable without network access. Backend CI runs `deno test`
// with no network and no Postgres, so `index.ts` deliberately keeps nothing but
// I/O wiring.

import { z } from "zod";

import type { Database } from "@src/types/database.types.ts";

import { type RetryAfter, withRetry } from "./retry.ts";

/** Mirrors the `public.sun_sign` enum, so the column type is the source of truth. */
export type TSunSign = Database["public"]["Enums"]["sun_sign"];

/**
 * The twelve sun signs, in astrological order.
 *
 * Lowercase because these strings double as the path segment AstrologyAPI
 * expects. Two independent guards keep this honest: `satisfies` makes a value
 * the enum does not contain a type error right here, and a migration test
 * asserts the list and the enum agree in length and order (the generated types
 * are regenerated by hand, so a typecheck alone could pass against stale ones).
 */
export const ZODIAC_SIGNS = [
  "aries",
  "taurus",
  "gemini",
  "cancer",
  "leo",
  "virgo",
  "libra",
  "scorpio",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
] as const satisfies readonly TSunSign[];

const API_BASE =
  "https://json.astrologyapi.com/v1/sun_sign_prediction/daily/next";

/** The six facets the upstream returns, which are also the column names. */
export const PREDICTION_FACETS = [
  "personal_life",
  "profession",
  "health",
  "emotions",
  "travel",
  "luck",
] as const;

// Exactly the six text facets, and nothing else. DEX-84's sample response (from
// 2024) also carried a `<facet>_rating` integer for each, but the live API no
// longer returns them — verified 2026-08-04 across four endpoints and two signs.
// Requiring them here would fail every sign; accepting them optionally would
// ship six columns that are always null. See the migration header.
export const predictionSchema = z.object({
  personal_life: z.string(),
  profession: z.string(),
  health: z.string(),
  emotions: z.string(),
  travel: z.string(),
  luck: z.string(),
});

export const predictionResponseSchema = z.object({
  sun_sign: z.string(),
  prediction_date: z.string(),
  prediction: predictionSchema,
});

export type TPrediction = z.infer<typeof predictionSchema>;
export type TPredictionResponse = z.infer<typeof predictionResponseSchema>;

/**
 * Converts AstrologyAPI's `D-M-YYYY` prediction date to an ISO `YYYY-MM-DD`
 * one for the `date` column.
 *
 * The upstream zero-pads neither the day nor the month (`"1-3-2024"`), and the
 * response date is used rather than a locally computed "tomorrow" on purpose:
 * the two can disagree, and the API's own answer is the one the text describes.
 */
export function parsePredictionDate(value: string): string {
  const match = value.trim().match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);
  if (!match) {
    throw new Error(`Unrecognized prediction_date: ${value}`);
  }
  const [, day, month, year] = match;
  const iso = `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;

  // A range check on the fields alone would let `31-2-2026` through as
  // `2026-02-31`, which Postgres rejects — and because all twelve rows go up in
  // one upsert, that would fail the whole batch rather than the one sign the
  // per-sign isolation is built to contain. The round-trip catches it: JS rolls
  // an impossible day over (`2026-02-31` → `2026-03-03`) instead of erroring,
  // so a value that comes back unchanged is a real calendar date.
  const parsed = new Date(`${iso}T00:00:00Z`);
  if (
    Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== iso
  ) {
    throw new Error(`Out-of-range prediction_date: ${value}`);
  }

  return iso;
}

/** A non-2xx from AstrologyAPI, carrying enough to judge whether to retry. */
export class AstrologyApiError extends Error implements RetryAfter {
  readonly retryAfterMs?: number;

  constructor(readonly status: number, sign: string, retryAfterMs?: number) {
    // The upstream echoes the key in some error bodies, so the body never
    // reaches the message that goes to Sentry or the caller.
    super(`AstrologyAPI returned ${status} for ${sign}`);
    this.name = "AstrologyApiError";
    this.retryAfterMs = retryAfterMs;
  }
}

/**
 * Whether an AstrologyAPI failure could plausibly succeed on another attempt.
 *
 * 429 and 5xx are the upstream having a moment. Any other 4xx is us — a bad key,
 * a bad sign — and no number of retries fixes it. A `TypeError` is how `fetch`
 * reports a connection that never completed.
 */
export function isRetryableAstrologyError(error: unknown): boolean {
  if (error instanceof AstrologyApiError) {
    return error.status === 429 || error.status >= 500;
  }
  return error instanceof TypeError;
}

function retryAfterMs(response: Response): number | undefined {
  const header = response.headers.get("retry-after");
  if (!header) return undefined;
  // Delta-seconds is the common form; an HTTP-date is legal but rare here.
  const seconds = Number(header);
  return Number.isFinite(seconds) && seconds >= 0 ? seconds * 1000 : undefined;
}

/**
 * Fetches tomorrow's prediction for one sign, retrying transient failures.
 *
 * `fetchImpl` is injected rather than stubbed onto `globalThis` so tests never
 * touch the network — the same dependency-injection shape `_shared/sentry.ts`
 * uses for its client.
 *
 * A schema mismatch is deliberately *not* retried: the call succeeded and the
 * upstream simply sent a shape we don't accept, which a second identical
 * request will send again.
 */
export function fetchPrediction(
  sign: TSunSign,
  apiKey: string,
  fetchImpl: typeof fetch = fetch,
  sleep?: (ms: number) => Promise<void>,
): Promise<TPredictionResponse> {
  return withRetry(async () => {
    const response = await fetchImpl(`${API_BASE}/${sign}`, {
      method: "POST",
      headers: {
        // Token auth. AstrologyAPI also accepts HTTP Basic with a user id and
        // key pair; the header form needs only the one secret.
        "x-astrologyapi-key": apiKey,
        "Content-Type": "application/json",
        "Accept-Language": "en",
      },
      body: JSON.stringify({}),
    });

    if (!response.ok) {
      throw new AstrologyApiError(
        response.status,
        sign,
        retryAfterMs(response),
      );
    }

    return predictionResponseSchema.parse(await response.json());
  }, {
    label: `AstrologyAPI ${sign}`,
    isRetryable: isRetryableAstrologyError,
    sleep,
  });
}
